
package ru.runa.wfe.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TaskAlreadyCompletedException", targetNamespace = "http://impl.service.wfe.runa.ru/")
public class TaskAlreadyCompletedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TaskAlreadyCompletedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TaskAlreadyCompletedException_Exception(String message, TaskAlreadyCompletedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TaskAlreadyCompletedException_Exception(String message, TaskAlreadyCompletedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.runa.wfe.webservice.TaskAlreadyCompletedException
     */
    public TaskAlreadyCompletedException getFaultInfo() {
        return faultInfo;
    }

}
