
package ru.runa.wfe.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BotInvokerAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BotInvokerAPI {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "cancelPeriodicBotsInvocation", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CancelPeriodicBotsInvocation")
    @ResponseWrapper(localName = "cancelPeriodicBotsInvocationResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CancelPeriodicBotsInvocationResponse")
    public void cancelPeriodicBotsInvocation();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "invokeBots", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.InvokeBots")
    @ResponseWrapper(localName = "invokeBotsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.InvokeBotsResponse")
    public void invokeBots(
        @WebParam(name = "arg0", targetNamespace = "")
        BotStation arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isRunning", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsRunning")
    @ResponseWrapper(localName = "isRunningResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsRunningResponse")
    public boolean isRunning();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "startPeriodicBotsInvocation", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.StartPeriodicBotsInvocation")
    @ResponseWrapper(localName = "startPeriodicBotsInvocationResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.StartPeriodicBotsInvocationResponse")
    public void startPeriodicBotsInvocation(
        @WebParam(name = "arg0", targetNamespace = "")
        BotStation arg0);

}
