
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LDAPSynchronizerWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/runawfe-wfe-service-4.0.0/LDAPSynchronizerServiceBean?wsdl")
public class LDAPSynchronizerWebService
    extends Service
{

    private final static URL LDAPSYNCHRONIZERWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException LDAPSYNCHRONIZERWEBSERVICE_EXCEPTION;
    private final static QName LDAPSYNCHRONIZERWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "LDAPSynchronizerWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/runawfe-wfe-service-4.0.0/LDAPSynchronizerServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LDAPSYNCHRONIZERWEBSERVICE_WSDL_LOCATION = url;
        LDAPSYNCHRONIZERWEBSERVICE_EXCEPTION = e;
    }

    public LDAPSynchronizerWebService() {
        super(__getWsdlLocation(), LDAPSYNCHRONIZERWEBSERVICE_QNAME);
    }

    public LDAPSynchronizerWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LDAPSYNCHRONIZERWEBSERVICE_QNAME, features);
    }

    public LDAPSynchronizerWebService(URL wsdlLocation) {
        super(wsdlLocation, LDAPSYNCHRONIZERWEBSERVICE_QNAME);
    }

    public LDAPSynchronizerWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LDAPSYNCHRONIZERWEBSERVICE_QNAME, features);
    }

    public LDAPSynchronizerWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LDAPSynchronizerWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LDAPSynchronizerAPI
     */
    @WebEndpoint(name = "LDAPSynchronizerAPIPort")
    public LDAPSynchronizerAPI getLDAPSynchronizerAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "LDAPSynchronizerAPIPort"), LDAPSynchronizerAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LDAPSynchronizerAPI
     */
    @WebEndpoint(name = "LDAPSynchronizerAPIPort")
    public LDAPSynchronizerAPI getLDAPSynchronizerAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "LDAPSynchronizerAPIPort"), LDAPSynchronizerAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LDAPSYNCHRONIZERWEBSERVICE_EXCEPTION!= null) {
            throw LDAPSYNCHRONIZERWEBSERVICE_EXCEPTION;
        }
        return LDAPSYNCHRONIZERWEBSERVICE_WSDL_LOCATION;
    }

}
