
package ru.runa.wfe.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DefinitionAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DefinitionAPI {


    /**
     * 
     * @param processTypes
     * @param processArchive
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deployProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeployProcessDefinition")
    @ResponseWrapper(localName = "deployProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeployProcessDefinitionResponse")
    public WfDefinition deployProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processArchive", targetNamespace = "")
        byte[] processArchive,
        @WebParam(name = "processTypes", targetNamespace = "")
        List<String> processTypes);

    /**
     * 
     * @param definitionName
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLatestProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetLatestProcessDefinition")
    @ResponseWrapper(localName = "getLatestProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetLatestProcessDefinitionResponse")
    public WfDefinition getLatestProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionName", targetNamespace = "")
        String definitionName);

    /**
     * 
     * @param batchPresentation
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfDefinition>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLatestProcessDefinitions", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetLatestProcessDefinitions")
    @ResponseWrapper(localName = "getLatestProcessDefinitionsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetLatestProcessDefinitionsResponse")
    public List<WfDefinition> getLatestProcessDefinitions(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation);

    /**
     * 
     * @param taskId
     * @param withTimerTransitions
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutputTransitionNames", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetOutputTransitionNames")
    @ResponseWrapper(localName = "getOutputTransitionNamesResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetOutputTransitionNamesResponse")
    public List<String> getOutputTransitionNames(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "taskId", targetNamespace = "")
        Long taskId,
        @WebParam(name = "withTimerTransitions", targetNamespace = "")
        boolean withTimerTransitions);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinition")
    @ResponseWrapper(localName = "getProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionResponse")
    public WfDefinition getProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param fileName
     * @param user
     * @param definitionId
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionFile", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionFile")
    @ResponseWrapper(localName = "getProcessDefinitionFileResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionFileResponse")
    public byte[] getProcessDefinitionFile(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.GraphElementPresentation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionGraphElements", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionGraphElements")
    @ResponseWrapper(localName = "getProcessDefinitionGraphElementsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionGraphElementsResponse")
    public List<GraphElementPresentation> getProcessDefinitionGraphElements(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param name
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfDefinition>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionHistory", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionHistory")
    @ResponseWrapper(localName = "getProcessDefinitionHistoryResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionHistoryResponse")
    public List<WfDefinition> getProcessDefinitionHistory(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns ru.runa.wfe.webservice.Interaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStartInteraction", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetStartInteraction")
    @ResponseWrapper(localName = "getStartInteractionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetStartInteractionResponse")
    public Interaction getStartInteraction(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.SwimlaneDefinition>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSwimlaneDefinitions", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSwimlaneDefinitions")
    @ResponseWrapper(localName = "getSwimlaneDefinitionsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSwimlaneDefinitionsResponse")
    public List<SwimlaneDefinition> getSwimlaneDefinitions(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param taskId
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.Interaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskInteraction", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskInteraction")
    @ResponseWrapper(localName = "getTaskInteractionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskInteractionResponse")
    public Interaction getTaskInteraction(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "taskId", targetNamespace = "")
        Long taskId);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.VariableDefinition>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVariableDefinitions", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableDefinitions")
    @ResponseWrapper(localName = "getVariableDefinitionsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableDefinitionsResponse")
    public List<VariableDefinition> getVariableDefinitions(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param processTypes
     * @param processId
     * @param processArchive
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "redeployProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RedeployProcessDefinition")
    @ResponseWrapper(localName = "redeployProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RedeployProcessDefinitionResponse")
    public WfDefinition redeployProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "processArchive", targetNamespace = "")
        byte[] processArchive,
        @WebParam(name = "processTypes", targetNamespace = "")
        List<String> processTypes);

    /**
     * 
     * @param definitionName
     * @param user
     * @param version
     */
    @WebMethod
    @RequestWrapper(localName = "removeProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveProcessDefinition")
    @ResponseWrapper(localName = "removeProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveProcessDefinitionResponse")
    public void removeProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionName", targetNamespace = "")
        String definitionName,
        @WebParam(name = "version", targetNamespace = "")
        int version);

    /**
     * 
     * @param processName
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "undeployProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UndeployProcessDefinition")
    @ResponseWrapper(localName = "undeployProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UndeployProcessDefinitionResponse")
    public void undeployProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processName", targetNamespace = "")
        String processName);

}
