
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BotInvokerWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/runawfe-wfe-service-4.0.0/BotInvokerServiceBean?wsdl")
public class BotInvokerWebService
    extends Service
{

    private final static URL BOTINVOKERWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOTINVOKERWEBSERVICE_EXCEPTION;
    private final static QName BOTINVOKERWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "BotInvokerWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/runawfe-wfe-service-4.0.0/BotInvokerServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOTINVOKERWEBSERVICE_WSDL_LOCATION = url;
        BOTINVOKERWEBSERVICE_EXCEPTION = e;
    }

    public BotInvokerWebService() {
        super(__getWsdlLocation(), BOTINVOKERWEBSERVICE_QNAME);
    }

    public BotInvokerWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOTINVOKERWEBSERVICE_QNAME, features);
    }

    public BotInvokerWebService(URL wsdlLocation) {
        super(wsdlLocation, BOTINVOKERWEBSERVICE_QNAME);
    }

    public BotInvokerWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOTINVOKERWEBSERVICE_QNAME, features);
    }

    public BotInvokerWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BotInvokerWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BotInvokerAPI
     */
    @WebEndpoint(name = "BotInvokerAPIPort")
    public BotInvokerAPI getBotInvokerAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "BotInvokerAPIPort"), BotInvokerAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BotInvokerAPI
     */
    @WebEndpoint(name = "BotInvokerAPIPort")
    public BotInvokerAPI getBotInvokerAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "BotInvokerAPIPort"), BotInvokerAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOTINVOKERWEBSERVICE_EXCEPTION!= null) {
            throw BOTINVOKERWEBSERVICE_EXCEPTION;
        }
        return BOTINVOKERWEBSERVICE_WSDL_LOCATION;
    }

}
