package ru.cg.runaex.components.bean.component;

/**
 * @author urmancheev
 */
public enum ComponentType {
  UNKNOWN,

  FLEXI_GRID,
  LINK_FLEXI_GRID,
  DEPENDENT_FLEXI_GRID,
  TREE_GRID,
  EDITABLE_TREE_GRID,
  SELECT_TREE_GRID,
  SELECT_FLEXI_GRID,

  AUTOCOMPLETE,
  CHECK_BOX,
  COMBO_BOX,
  DATE_TIME_PICKER,
  RADIO_BUTTON_GROUP,
  TEXT_FIELD,
  FILE_UPLOAD,
  FILE_VIEW,
  HIDDEN_INPUT,
  FIAS_ADDRESS,
  SPHINX_SEARCH,
  RECORD_NUMBER_GENERATOR,
  NUMBER_FIELD,

  FILTER_FIELD,
  FILTER_NUMBER_FIELD,
  FILTER_AUTOCOMPLETE,
  FILTER_CHECKBOX,
  FILTER_COMBO_BOX,
  FILTER_DATE_TIME_PICKER,
  FILTER_RADIO_BUTTON_GROUP,
  FILTER_FIAS_ADDRESS,

  PRINT_BUTTON,
  ACTION_BUTTON,
  SIGN_AND_SAVE_BUTTON,
  EXECUTE_GROOVY_BUTTON,
  NAVIGATE_BUTTON,
  HELP_BUTTON,
  NAVIGATION_TREE_MENU,

  LABEL,

  SIGN_VERIFY,

  TIMER,

  GROOVY_RULE
}
