#!/bin/sh
#
# runawfe - runawfe server
#
# chkconfig: 2345 99 1
# processname: runawfe
# config: /etc/runawfe
# pidfile: /var/run/runawfe.pid
#
### BEGIN INIT INFO
# Provides: runawfe
# Default-Start: 2 3 4 5
# Short-Description: runawfe server
# Description: runawfe server or botstation daemon
### END INIT INFO

# Do not load RH compatibility interface.
WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

PIDFILE=/var/run/template.pid
LOCKFILE=/var/lock/subsys/template
RETVAL=0
PROGRAM="/usr/sbin/runawfe-start.sh"

start()
{
	start_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- $PROGRAM
	RETVAL=$?
	return $RETVAL
}

stop()
{
	/usr/sbin/runawfe-stop.sh
	stop_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- $PROGRAM
	RETVAL=$?
	rm -f /var/lock/subsys/runawfe
	return $RETVAL
}

restart()
{
	stop
	start
}

reload()
{
	msg_reloading $PROGRAM
	stop_daemon --pidfile "$PIDFILE" --expect-user root -HUP -- $PROGRAM
	RETVAL=$?
	return $RETVAL
} 

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		reload
		;;
	restart)
		restart
		;;
	condstop)
		if [ -e "$LOCKFILE" ]; then
			stop
		fi
		;;
	condrestart)
		if [ -e "$LOCKFILE" ]; then
			restart
		fi
		;;
	condreload)
		if [ -e "$LOCKFILE" ]; then
			reload
		fi
		;;
	status)
		status --pidfile "$PIDFILE" --expect-user root -- template
		RETVAL=$?
		;;
	*)
		msg_usage "${0##*/} {start|stop|reload|restart|condstop|condrestart|condreload|status}"
		RETVAL=1
esac

exit $RETVAL
