
package ru.runa.wfe.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProfileAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProfileAPI {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.runa.wfe.webservice.Profile
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBatchPresentation", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CreateBatchPresentation")
    @ResponseWrapper(localName = "createBatchPresentationResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CreateBatchPresentationResponse")
    public Profile createBatchPresentation(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BatchPresentation arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.runa.wfe.webservice.Profile
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBatchPresentation", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteBatchPresentation")
    @ResponseWrapper(localName = "deleteBatchPresentationResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteBatchPresentationResponse")
    public Profile deleteBatchPresentation(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BatchPresentation arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.runa.wfe.webservice.Profile
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProfile", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProfile")
    @ResponseWrapper(localName = "getProfileResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProfileResponse")
    public Profile getProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.runa.wfe.webservice.Profile
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveBatchPresentation", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SaveBatchPresentation")
    @ResponseWrapper(localName = "saveBatchPresentationResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SaveBatchPresentationResponse")
    public Profile saveBatchPresentation(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BatchPresentation arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.runa.wfe.webservice.Profile
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setActiveBatchPresentation", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SetActiveBatchPresentation")
    @ResponseWrapper(localName = "setActiveBatchPresentationResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SetActiveBatchPresentationResponse")
    public Profile setActiveBatchPresentation(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
